name: Run Data Pipeline Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Convert line endings for tests.sh
        run: |
          sudo apt-get install dos2unix
          dos2unix made-template/project/tests.sh

      - name: Run tests
        run: |
          cd made-template/project
          chmod +x tests.sh
          ./tests.sh
